export const USER_NOT_AUTHORIZED_REASON = 'USER_NOT_AUTHORIZED';
export const USER_NOT_FOUND_REASON = 'USER_NOT_FOUND';
export const USER_ALREADY_EXISTS_REASON = 'USER_ALREADY_EXISTS';
export const UNKNOWN_ERROR_REASON = 'UNKNOWN_ERROR';
